name: Bun CI

on: [push]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v1
      - uses: actions/checkout@v4
      - name: bun install
        run: |
          bun install
      - name: bun run lint
        run: |
          bun run lint
      - name: bun run check
        run: |
          bun run check
      - name: bun run build
        run: |
          bun run build
      - name: deploy
        if: github.ref == 'refs/heads/main'
        uses: ayeressian/bunnycdn-storage-deploy@v2.2.3
        with:
          source: 'dist/'
          destination: '/'
          storageZoneName: '${{ secrets.BUNNY_STORAGE_NAME }}'
          storagePassword: '${{ secrets.BUNNY_STORAGE_PASSWORD }}'
          storageEndpoint: '${{ secrets.BUNNY_STORAGE_ENDPOINT }}'
          accessKey: '${{ secrets.BUNNY_API_KEY }}'
          pullZoneId: '${{ secrets.BUNNY_ZONE_ID }}'
          upload: 'true'
          remove: 'true'
          purgePullZone: 'true'
