name: Check for dead links

on:
  push:
    branches:
      - main

jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: '**/*.md'
          timeout: 30000
          linksToSkip: 'https://example.com/my-link,https://sevenseasentertainment.com/2020/02/20/seven-seas-has-a-type-with-license-of-what-the-font-a-manga-guide-to-western-typeface/,https://www.fiio.com/btr5,https://velocity.silverlakesoftware.com/,https://imageoptim.com/mac,https://www.kickstarter.com/projects/cryptonfuturemedia/hatsune-miku-global-concert-hatsune-miku-expo-2023-vr,https://1blocker.com/'
