name: Node CI

on: [push]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          npm ci
      - name: npm run lint
        run: |
          npm run lint
      - name: npm run check
        run: |
          npm run check
      - name: npm build
        run: |
          npm run build --if-present
      - name: deploy
        if: github.ref == 'refs/heads/main'
        uses: ayeressian/bunnycdn-storage-deploy@v2.2.3
        with:
          source: 'dist/'
          destination: '/'
          storageZoneName: '${{ secrets.BUNNY_STORAGE_NAME }}'
          storagePassword: '${{ secrets.BUNNY_STORAGE_PASSWORD }}'
          storageEndpoint: '${{ secrets.BUNNY_STORAGE_ENDPOINT }}'
          accessKey: '${{ secrets.BUNNY_API_KEY }}'
          pullZoneId: '${{ secrets.BUNNY_ZONE_ID }}'
          upload: 'true'
          remove: 'true'
          purgePullZone: 'true'
