name: Node CI

env:
  ASTRO_STUDIO_APP_TOKEN: ${{ secrets.ASTRO_STUDIO_APP_TOKEN }}

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          npm ci
      - name: astro build
        run: |
          npm run build --if-present
      - name: prettier lint
        run: |
          npm run lint
      - name: astro check
        run: |
          npm run check
        env:
          CI: true
